from queue import LifoQueue
s=LifoQueue(maxsize=6)
print(s.qsize())
s.put(1)
s.put(2)
s.put(3)
s.put(4)
s.put(5)
s.put(6)
print(s.full())
print(s.qsize())
print(s.get())
print(s.get())
print(s.get())
print(s.get())
print(s.get())
print(s.get())
print(s.empty())
